[package]
name = "space-together-api"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/space-together/space-together-api"
description = "space-together-api which implements all request from space-together applications."
authors = ["Rwanda Bruno Happyheart <brunorwanda4@gmail.com>"]

[dependencies]
actix-web = "4.9.0"
actix-web-actors = "4.2.0"  # WebSockets support
actix = "0.13.3"            # Actix actor system (for WebSockets)
config = "0.10.1"
dotenv = "0.15.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_with = "3.11.0"
tokio = { version = "1.41.1", features = ["full"] }
slog = "2.5.2"
slog-term = "2.5.0"
slog-async = "2.4.0"
slog-envlogger = "2.2.0"
futures = "0.3.31"
futures-util = "0.3.31"
regex = "1.11.1"
rand = "0.8.5"
itertools = "0.13.0"
actix-cors = "0.7.0"
jsonwebtoken = "9.3.0"
lazy_static = "1.4.0"
chrono = "0.4.39"
actix-web-lab = "0.20.0"
bcrypt = "0.16.0"
aes-gcm = "0.10"
base64 = "0.21"

# WebSocket support
actix-ws = "0.3.0"   # Already included, but actix-web-actors is needed for full WebSocket support
actix-identity = "0.8.0"
actix-session = "0.10.1"
async-trait = "0.1.88"
env_logger = "0.11.7"
tracing = "0.1.41"
reqwest = {version = "0.12.15", features = ["json"]}
sha2 = "0.10.8"

[dependencies.mongodb]
version = "3.1.0"
features = ["sync"]

[[bin]]
name = "space-together-api"
path = "src/main.rs"

[profile.dev]
incremental = true