version: "3.8"
services:
  rust-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2052:2052"
    volumes:
      - ./src:/app/src
      - ./target:/app/target
    command: ["cargo", "watch", "-q", "-c", "-w", "src/", "-x", "run"]
