version: "3.8"

services:
  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2052:2052"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://mongodb:27017"
    command: ["/space-together-api"]
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
