version: '3.9'

services:
  space-together-api:
  container_name: space-together-api
  image : bruno_rwanda/space-together-api:0.0.2
  build:
    context: .
    dockerfile: dockerfile
    args:
     DATABASE_URL: mongodb://localhost:27017
  ports: 
    - '20044:20044'
  depends_on:
    - db
  
      